"""
Deterministic Offline Fallback Provider.

Provides deterministic tool execution responses when API keys are not supplied or for testing.
"""

import json
from typing import Dict, Any, List, Optional
from app.providers.base import BaseLLMProvider, ProviderResponse, ToolCallRequest


class OfflineProvider(BaseLLMProvider):
    """Deterministic offline provider implementing keyword-based tool matching."""

    def __init__(self, model_name: str = "deterministic-offline"):
        super().__init__(provider_name="offline", model_name=model_name)

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        tools: Optional[List[Dict[str, Any]]] = None,
        max_tokens: int = 1024,
        temperature: float = 0.2
    ) -> ProviderResponse:
        # Extract user directive
        user_msg = ""
        for m in reversed(messages):
            if m.get("role") == "user":
                user_msg = m.get("content", "").lower()
                break

        # Check for tool invocations
        if "list" in user_msg or "files" in user_msg or "directory" in user_msg:
            return ProviderResponse(
                content=None,
                tool_calls=[
                    ToolCallRequest(
                        id="call_offline_list_1",
                        tool_name="list_files",
                        arguments={"sub_dir": "."}
                    )
                ],
                finish_reason="tool_calls"
            )
        elif "read" in user_msg and ("file" in user_msg or "notes" in user_msg):
            return ProviderResponse(
                content=None,
                tool_calls=[
                    ToolCallRequest(
                        id="call_offline_read_1",
                        tool_name="read_file",
                        arguments={"file_path": "notes.txt"}
                    )
                ],
                finish_reason="tool_calls"
            )
        elif "schema" in user_msg or "database" in user_msg or "tables" in user_msg:
            return ProviderResponse(
                content=None,
                tool_calls=[
                    ToolCallRequest(
                        id="call_offline_schema_1",
                        tool_name="inspect_schema",
                        arguments={"db_filename": "app_data.db"}
                    )
                ],
                finish_reason="tool_calls"
            )
        elif "write" in user_msg or "create" in user_msg:
            return ProviderResponse(
                content=None,
                tool_calls=[
                    ToolCallRequest(
                        id="call_offline_write_1",
                        tool_name="write_file",
                        arguments={"file_path": "output.txt", "content": "Sample content generated by agent."}
                    )
                ],
                finish_reason="tool_calls"
            )
        elif "delete" in user_msg or "remove" in user_msg:
            return ProviderResponse(
                content=None,
                tool_calls=[
                    ToolCallRequest(
                        id="call_offline_delete_1",
                        tool_name="delete_file",
                        arguments={"file_path": "to_delete.txt"}
                    )
                ],
                finish_reason="tool_calls"
            )
        else:
            return ProviderResponse(
                content=f"[Offline Fallback] Processed directive: '{messages[-1].get('content', '')}'. Workspace operational.",
                tool_calls=[],
                finish_reason="stop"
            )
